steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'services/research-worker/Dockerfile', '-t', 'us-west1-docker.pkg.dev/hiddenfeed/atlas-research/worker:${_TAG}', '.']
images:
  - 'us-west1-docker.pkg.dev/hiddenfeed/atlas-research/worker:${_TAG}'
options:
  logging: CLOUD_LOGGING_ONLY
